// src/app/channels/channel-epg/channel-epg.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';
import { EpgEntry } from '../../entities/epg-entry';
import { epgInAir } from '@store/reducers/epg.reducer';

@Component({
  selector: 'channel-epg',
  template: `
    <div class="host">
      <div class="entries">
        <div class="entry" *ngFor="let entry of filterOutdatedEntries(entries); trackBy: trackEntries">
          <div class="mainInfo">
            <h5 class="name">{{entry.name}}</h5>

            <div class="timing">
              <div class="start-time">{{entry.startTime | time}}</div>
              <div class="end-time">{{entry.endTime | time}}</div>
            </div>
          </div>

          <div class="side-info">
            <span class="date">{{entry.startTime | date}}</span>
            <span class="duration">{{entry.duration | duration}}</span>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./channel-epg.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChannelEpgComponent {
  @Input() public entries: EpgEntry[];

  public trackEntries(index: number, entry: EpgEntry) {
    return entry.startTime;
  }

  public filterOutdatedEntries(entries: EpgEntry[]) {
    const index = entries.findIndex(epgInAir);
    return entries.slice(index + 1);

  }
}

// src/components/channel-epg/channel-epg.tsx
import React, { PureComponent } from 'react';
import { epgInAir } from '../../store/reducers/epg.reducer';
import styles from './channel-epg.scss';
import { ProgressBar } from '../progress-bar/progress-bar';
import { EpgEntry } from '../../entities/epg-entry';
import { Time } from '../formatters/time';
import Scrollbars from 'react-custom-scrollbars';
import { Duration } from '../formatters/duration';
import { DateFormatter } from '../formatters/date';

export interface StateProps {
  entries: EpgEntry[];
}

export interface OwnProps {
  channelId: number;
}

type Props = StateProps & OwnProps;

export class ChannelEpgComponent extends PureComponent<Props> {
  public render() {
    return (
      <div className={styles.host}>
        <Scrollbars autoHide>
          <div className={styles.entries}>

            {this.props.entries.map((entry) => (
              <div className={epgInAir(entry) ? styles.entryActive : styles.entry} key={entry.startTime}>

                <div className={styles.mainInfo}>
                  <h5 className={styles.name}>{entry.name}</h5>

                  {epgInAir(entry) && <ProgressBar startTime={entry.startTime} endTime={entry.endTime}/>}

                  {!epgInAir(entry) && (
                    <div className={styles.timing}>
                      <div className={styles.startTime}><Time>{entry.startTime}</Time></div>
                      <div className={styles.endTime}><Time>{entry.endTime}</Time></div>
                    </div>
                  )}

                </div>

                <div className={styles.sideInfo}>
                  <span className={styles.date}><DateFormatter>{entry.startTime}</DateFormatter></span>
                  <span className={styles.duration}><Duration>{entry.duration}</Duration></span>
                </div>

              </div>
            ))}

          </div>
        </Scrollbars>
      </div>
    );
  }
}
