// src/app/channels/player-area/player-area.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { AppState } from '@store';
import { Store } from '@ngrx/store';
import { epgInAir, selectChannelEpg } from '@store/reducers/epg.reducer';
import { ToggleMainPanel } from '@store/actions/ui.actions';
import { EpgEntry } from '../../entities/epg-entry';
import { selectCurrentChannel, selectStreamUrl } from '@store/reducers/channels.reducer';
import { selectCastingEnabled } from '@store/reducers/casting.reducer';
import { map, distinctUntilChanged } from 'rxjs/internal/operators';

@Component({
  selector: 'player-area',
  templateUrl: './player-area.component.html',
  styleUrls: ['./player-area.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlayerAreaComponent  {
  public currentChannel$ = this.store.select(selectCurrentChannel);
  public isCastingEnabled$ = this.store.select(selectCastingEnabled);
  public streamUrl$ = this.store.select(selectStreamUrl);
  public epg$ = this.store.select((state) => selectChannelEpg(state, state.channels.selectedChannelId)).pipe(
    map((entries) => entries.find(epgInAir) || ({} as EpgEntry)),
    distinctUntilChanged(),
  );

  constructor(
    private store: Store<AppState>
  ) {}

  public goBack() {
    this.store.dispatch(new ToggleMainPanel({ visible: false }));
  }
}


<div class="main-panel">
  <div class="top-controls">
    <button type='button' (click)="goBack()" class="back-btn">
      <!--<ArrowLeft/>-->
    </button>
  </div>

  <div class="playerContainer" *ngIf="isCastingEnabled$ | async">
    <!--<VideoPlayer src={streamUrl$ | async}/>-->
  </div>


  <div class="under-wrap" *ngIf="epg$ | async as epg">
    <div class="progress">
      <progress-bar [startTime]="epg.startTime" [endTime]="epg.endTime"></progress-bar>
    </div>

    <!--<Scrollbars autoHide>-->
      <div class="video-details">
        <div class="program-details">
          <div class="program-name">
            {{epg.name}}
          </div>

          <div class="program-timebox">
            {{epg.startTime | time}} - {{epg.endTime | time}} {{epg.endTime - epg.startTime | duration}}
          </div>

          <div class="program-description">
            {{epg.descr}}
          </div>
        </div>

        <div class="channel-details" *ngIf="(currentChannel$ | async) as currentChannel">
          <div class="channel-logo">
            <img [src]="currentChannel.logo"/>
          </div>

          <div class="channel-name">
            {{currentChannel.name}}
          </div>
        </div>
      </div>

      <channel-epg *ngIf="(currentChannel$ | async) as currentChannel"
                   [channelId]="currentChannel.id">
      </channel-epg>
    <!--</Scrollbars>-->
  </div>
</div>

// src/components/player-area/player-area.component.tsx
import React, { PureComponent } from 'react';
import { VideoPlayer } from '../video-player/video-player';
import styles from './player-area.scss';
import { Channel } from '../../entities/channel.model';
import { ChannelEpg } from '../channel-epg/channel-epg.container';
import { AppState } from '../../store';
import { connect } from 'react-redux';
import { selectCurrentChannel } from '../../store/reducers/channels.reducer';
import Scrollbars from 'react-custom-scrollbars';
import ArrowLeft from 'react-icons/lib/md/chevron-left';
import autobind from 'autobind-decorator';
import { EpgEntry } from '../../entities/epg-entry';
import { epgInAir, selectChannelEpg } from '../../store/reducers/epg.reducer';
import { ProgressBar } from '../progress-bar/progress-bar';
import { Time } from '../formatters/time';
import { Duration } from '../formatters/duration';
import { Dispatch } from 'redux';
import { ToggleMainPanel } from '../../store/actions/ui.actions';

interface Props {
  currentChannel: Readonly<Channel>;
  currentKey: string;
  castingSessionState: cast.framework.SessionState;
  epg: EpgEntry[];
  onTogglePanel: () => void;
}

class PlayerAreaComponent extends PureComponent<Props> {
  public getStreamUrl(channel: Channel) {
    return ((channel && channel.stream) || '')
      .replace('{KEY}', this.props.currentKey);
  }

  public componentWillReceiveProps(nextProps: Props) {
    this.setMediaToCast(nextProps.castingSessionState, nextProps.currentChannel);
  }

  private setMediaToCast(sessionState: string, channel: Channel) {
    if (!this.isCastingEnabled(sessionState) || !channel) {
      return;
    }

    // todo, extract to side effects
    const media: any = chrome.cast.media;
    const castSession = cast.framework.CastContext.getInstance().getCurrentSession();

    const mediaInfo = new media.MediaInfo(this.getStreamUrl(channel), 'application/x-mpegURL');
    const request = new media.LoadRequest(mediaInfo);

    mediaInfo.metadata = new media.GenericMediaMetadata();
    mediaInfo.metadata.title = channel.name;

    castSession.loadMedia(request);
  }

  private isCastingEnabled(sessionState: string): boolean {
    return ['SESSION_STARTED', 'SESSION_RESUMED'].includes(sessionState);
  }

  @autobind
  private goBack() {
    this.props.onTogglePanel();
  }

  public render() {
    const epg = this.props.epg.find(epgInAir) || ({} as EpgEntry);

    if (!this.props.currentChannel) {
      return null;
    }

    return (
      <div className={styles.mainPanel}>
        <div className={styles.topControls}>
          <button type='button' onClick={this.goBack} className={styles.backBtn}><ArrowLeft/>
          </button>
        </div>

        {!this.isCastingEnabled(this.props.castingSessionState) && (
          <div className={styles.playerContainer}>
            <VideoPlayer src={this.getStreamUrl(this.props.currentChannel)}/>
          </div>
        )}

        <div className={styles.underWrap}>
          <div className={styles.progress}>
            <ProgressBar startTime={epg.startTime} endTime={epg.endTime}/>
          </div>

          <Scrollbars autoHide>
            <div className={styles.videoDetails}>
              <div className={styles.programDetails}>
                <div className={styles.programName}>
                  {epg.name}
                </div>

                <div className={styles.programTimebox}>
                  <Time>{epg.startTime}</Time> - <Time>{epg.endTime}</Time> (<Duration>{epg.endTime - epg.startTime}</Duration>)
                </div>

                <div className={styles.programDescription}>
                  {epg.descr}
                </div>
              </div>

              <div className={styles.channelDetails}>
                <div className={styles.channelLogo}>
                  <img src={this.props.currentChannel.logo}/>
                </div>

                <div className={styles.channelName}>
                  {this.props.currentChannel.name}
                </div>
              </div>
            </div>
            {this.props.currentChannel && <ChannelEpg channelId={this.props.currentChannel.id}/>}
          </Scrollbars>
        </div>
      </div>
    );
  }
}

function mapStateToProps(state: AppState): Partial<Props> {
  return {
    currentKey: state.settings.currentKey,
    castingSessionState: state.casting.sessionState,
    currentChannel: selectCurrentChannel(state),
    epg: selectChannelEpg(state, state.channels.selectedChannelId),
  };
}

function mapDispatchToProps(dispatch: Dispatch): Partial<Props> {
  return {
    onTogglePanel: () => dispatch(new ToggleMainPanel({ visible: false })),
  };
}

export const PlayerArea = connect(mapStateToProps, mapDispatchToProps)(PlayerAreaComponent);
