// src/components/cast-button/cast-button.tsx
import React, {PureComponent} from 'react';
import {connect} from 'react-redux';
import {AppState} from '../../store';
import Cast from 'react-icons/lib/md/cast';
import CastConnected from 'react-icons/lib/md/cast-connected';
import styles from './cast-button.scss';
import autobind from 'autobind-decorator';

export interface StateProps {
  castState: cast.framework.CastState;
}

type Props = StateProps;

export class CastButtonComponent extends PureComponent<Props> {
  private isConnected(): boolean {
    return this.props.castState === 'CONNECTED';
  }

  @autobind
  private requestCastSession() {
    const context = cast.framework.CastContext.getInstance();
    context.requestSession();
  }

  public render() {
    return <button className={this.isConnected() ? styles.active : styles.default}
            onClick={this.requestCastSession}
            title='Cast to...'
            type='button'>
      {this.isConnected() ? <CastConnected/> : <Cast/> }
    </button>;
  }
}

const mapStateToProps = (state: AppState): Props => {
  return {
    castState: state.casting.castState,
  };
};

export const CastButton = connect<StateProps>(
  mapStateToProps,
)(CastButtonComponent);

// src/app/shared/components/cast-button/cast-button.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@store';

@Component({
  selector: 'cast-button',
  template: `
    <button [class]="(isConnected$ | async) ? 'active' : 'default'"
            (click)="requestCastSession()"
            title='Cast to...'
            type='button'>
      {{(isConnected$ | async) ? 'connected icon' : 'cast icon'}}
    </button>
  `,
  styleUrls: ['./cast-button.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CastButtonComponent {
  public isConnected$ = this.store.select((state) => state.casting.castState  === 'CONNECTED');

  constructor(private store: Store<AppState>) {}

  public requestCastSession() {
    const context = cast.framework.CastContext.getInstance();
    context.requestSession();
  }
}
