// src/app/channels/channels-panel/channels-panel.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@store';
import { Group } from '@store/reducers/channels.reducer';
import { SetActiveGroup } from '@store/actions/channels.actions';

@Component({
  selector: 'channels-panel',
  template: `
    <div class="panel-wrap">
      <div class="header">
        <h3 class="header-title">Channels</h3>
      </div>
      <div class="body">
        <!--<tabs-component *ngIf="channels.length"-->
        <!--[items]="this.props.groups"-->
        <!--(onSelect)="handleSelectGroup($event)"-->
        <!--[selected]="selectedGroup.name"/>-->
        <div class="list">
          <channels-list
            [channels]="channels$ | async"
            [selectedChannelId]="selectedChannelId$ | async"
            [visibleIds]="visibleChannels$ | async"
          ></channels-list>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./channels-panel.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ChannelsPanelComponent {
  public channels$ = this.store.select((state) => state.channels.channels);
  public selectedChannelId$ = this.store.select((state) => state.channels.selectedChannelId);
  public visibleChannels$ = this.store.select(
    (state) =>
      state.channels.groups.find((group) => group.name === state.channels.selectedGroup).channels,
  );

  constructor(
    private store: Store<AppState>,
  ) {}

  public handleSelectGroup(group: Group) {
    this.store.dispatch(new SetActiveGroup({ name: group.name }));
  }
}

// src/components/channels-panel/channels-panel.tsx
import React, { PureComponent } from 'react';
import { Channel } from '../../entities/channel.model';
import { ChannelsList } from '../channels/channels-list/channels-list';
import { TabsComponent } from '../tabs/tabs';
import { ChannelsState, Group } from '../../store/reducers/channels.reducer';
import styles from './channels-panel.scss';

export interface OwnProps {
  onChangeChannel: (channel: Channel) => void;
  currentChannel: Channel;
}

export interface StateProps {
  favourites: ChannelsState['favourites'];
  channels: ChannelsState['channels'];
  groups: ChannelsState['groups'];
  selectedGroup: Group;
}

export interface DispatchProps {
  onSelectGroup: (group: { name: string }) => void;
}

type Props = OwnProps & StateProps & DispatchProps;

export class ChannelsPanelComponent extends PureComponent<Props> {
  private getList() {
    const props = {
      channels: this.props.channels,
      current: this.props.currentChannel,
      onChangeChannel: this.props.onChangeChannel,
      visibleIds: this.props.selectedGroup ? this.props.selectedGroup.channels : [],
    };

    return <ChannelsList {...props} />;
  }

  public render() {
    return (
      <div className={styles.host}>
        <div className={styles.header}>
          <h3 className={styles.headerTitle}>Channels</h3>
        </div>
        <div className={styles.body}>
          {this.props.channels.length ? (
            <TabsComponent items={this.props.groups}
                           onSelect={this.props.onSelectGroup}
                           selected={this.props.selectedGroup.name}/>
          ) : null}
          <div className={styles.list}>{this.getList()}</div>
        </div>
      </div>
    );
  }
}
